name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP Action
      uses: shivammathur/setup-php@1.8.7
      with:
        # Setup PHP version.
        php-version: 7.4
        # Setup PHP extensions.
        extensions: ffi
        # Setup code coverage driver.
        coverage: pcov

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --dev --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: |
        mkdir -p build/logs
        ./vendor/bin/phpunit --coverage-html build/logs/coverage-html --coverage-clover build/logs/clover.xml

    - name: Send to coveralls
      run: ./vendor/bin/php-coveralls -v
      env:
        COVERALLS_RUN_LOCALLY: 1
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

    - name: Run phpcs
      run: composer run-script phpcs

    - name: Run psalm
      run: ./vendor/bin/psalm --shepherd --output-format=github
